/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Configuration capability. */
public class Capability extends EnumValueCapability {
  protected transient long swigCPtr;

  protected Capability(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.Capability_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Capability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_Capability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** Value can be read. */
  public static final Capability GET = new Capability(classesJNI.Capability_GET_get(), false);

  /** Value can be written. */
  public static final Capability SET = new Capability(classesJNI.Capability_SET_get(), false);

  /** Possible values can be enumerated. */
  public static final Capability LIST = new Capability(classesJNI.Capability_LIST_get(), false);


  public static Capability getGET() {
    long cPtr = classesJNI.Capability_GET_get();
    return (cPtr == 0) ? null : new Capability(cPtr, false);
  }

  public static Capability getSET() {
    long cPtr = classesJNI.Capability_SET_get();
    return (cPtr == 0) ? null : new Capability(cPtr, false);
  }

  public static Capability getLIST() {
    long cPtr = classesJNI.Capability_LIST_get();
    return (cPtr == 0) ? null : new Capability(cPtr, false);
  }

}
