/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class CapabilityVector {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CapabilityVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CapabilityVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_CapabilityVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CapabilityVector() {
    this(classesJNI.new_CapabilityVector__SWIG_0(), true);
  }

  public CapabilityVector(long n) {
    this(classesJNI.new_CapabilityVector__SWIG_1(n), true);
  }

  public long size() {
    return classesJNI.CapabilityVector_size(swigCPtr, this);
  }

  public long capacity() {
    return classesJNI.CapabilityVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    classesJNI.CapabilityVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return classesJNI.CapabilityVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.CapabilityVector_clear(swigCPtr, this);
  }

  public void add(Capability x) {
    classesJNI.CapabilityVector_add(swigCPtr, this, Capability.getCPtr(x), x);
  }

  public Capability get(int i) {
    long cPtr = classesJNI.CapabilityVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Capability(cPtr, false);
  }

  public void set(int i, Capability val) {
    classesJNI.CapabilityVector_set(swigCPtr, this, i, Capability.getCPtr(val), val);
  }

}
