/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** A channel on a device. */
public class Channel {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Channel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Channel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_Channel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** Current name of this channel. */
public String name() {
    return classesJNI.Channel_name(swigCPtr, this);
  }

  /** Set the name of this channel. */
public void set_name(String name) {
    classesJNI.Channel_set_name(swigCPtr, this, name);
  }

  /** Type of this channel. */
public ChannelType type() {
    long cPtr = classesJNI.Channel_type(swigCPtr, this);
    return (cPtr == 0) ? null : new ChannelType(cPtr, false);
  }

  /** Enabled status of this channel. */
public boolean enabled() {
    return classesJNI.Channel_enabled(swigCPtr, this);
  }

  /** Set the enabled status of this channel.
   * @param value Boolean value to set. */
public void set_enabled(boolean value) {
    classesJNI.Channel_set_enabled(swigCPtr, this, value);
  }

  /** Get the index number of this channel. */
public long index() {
    return classesJNI.Channel_index(swigCPtr, this);
  }

}
