/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class ChannelGroupMap {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChannelGroupMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelGroupMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_ChannelGroupMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChannelGroupMap() {
    this(classesJNI.new_ChannelGroupMap__SWIG_0(), true);
  }

  public ChannelGroupMap(ChannelGroupMap arg0) {
    this(classesJNI.new_ChannelGroupMap__SWIG_1(ChannelGroupMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return classesJNI.ChannelGroupMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return classesJNI.ChannelGroupMap_empty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.ChannelGroupMap_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__shared_ptrT_sigrok__ChannelGroup_t get(String key) {
    return new SWIGTYPE_p_std__shared_ptrT_sigrok__ChannelGroup_t(classesJNI.ChannelGroupMap_get(swigCPtr, this, key), false);
  }

  public void set(String key, SWIGTYPE_p_std__shared_ptrT_sigrok__ChannelGroup_t x) {
    classesJNI.ChannelGroupMap_set(swigCPtr, this, key, SWIGTYPE_p_std__shared_ptrT_sigrok__ChannelGroup_t.getCPtr(x));
  }

  public void del(String key) {
    classesJNI.ChannelGroupMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return classesJNI.ChannelGroupMap_has_key(swigCPtr, this, key);
  }

}
