/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class ChannelVector {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChannelVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_ChannelVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChannelVector() {
    this(classesJNI.new_ChannelVector__SWIG_0(), true);
  }

  public ChannelVector(long n) {
    this(classesJNI.new_ChannelVector__SWIG_1(n), true);
  }

  public long size() {
    return classesJNI.ChannelVector_size(swigCPtr, this);
  }

  public long capacity() {
    return classesJNI.ChannelVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    classesJNI.ChannelVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return classesJNI.ChannelVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.ChannelVector_clear(swigCPtr, this);
  }

  public void add(SWIGTYPE_p_std__shared_ptrT_sigrok__Channel_t x) {
    classesJNI.ChannelVector_add(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_sigrok__Channel_t.getCPtr(x));
  }

  public SWIGTYPE_p_std__shared_ptrT_sigrok__Channel_t get(int i) {
    return new SWIGTYPE_p_std__shared_ptrT_sigrok__Channel_t(classesJNI.ChannelVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SWIGTYPE_p_std__shared_ptrT_sigrok__Channel_t val) {
    classesJNI.ChannelVector_set(swigCPtr, this, i, SWIGTYPE_p_std__shared_ptrT_sigrok__Channel_t.getCPtr(val));
  }

}
