/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Channel type. */
public class ChannelType extends EnumValueChannelType {
  protected transient long swigCPtr;

  protected ChannelType(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.ChannelType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_ChannelType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** Channel type is logic channel. */
  public static final ChannelType LOGIC = new ChannelType(classesJNI.ChannelType_LOGIC_get(), false);

  /** Channel type is analog channel. */
  public static final ChannelType ANALOG = new ChannelType(classesJNI.ChannelType_ANALOG_get(), false);


  public static ChannelType getLOGIC() {
    long cPtr = classesJNI.ChannelType_LOGIC_get();
    return (cPtr == 0) ? null : new ChannelType(cPtr, false);
  }

  public static ChannelType getANALOG() {
    long cPtr = classesJNI.ChannelType_ANALOG_get();
    return (cPtr == 0) ? null : new ChannelType(cPtr, false);
  }

}
