/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** A group of channels on a device, which share some configuration. */
public class ChannelGroup extends Configurable {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwnDerived;

  protected ChannelGroup(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.ChannelGroup_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        classesJNI.delete_ChannelGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** Name of this channel group. */
public String name() {
    return classesJNI.ChannelGroup_name(swigCPtr, this);
  }

  /** List of the channels in this group. */
public java.util.Vector<Channel> channels() {
  return (java.util.Vector<Channel>)classesJNI.ChannelGroup_channels(swigCPtr, this);
}

}
