/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class ConfigMap {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConfigMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfigMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_ConfigMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ConfigMap() {
    this(classesJNI.new_ConfigMap__SWIG_0(), true);
  }

  public ConfigMap(ConfigMap arg0) {
    this(classesJNI.new_ConfigMap__SWIG_1(ConfigMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return classesJNI.ConfigMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return classesJNI.ConfigMap_empty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.ConfigMap_clear(swigCPtr, this);
  }

  public Variant get(ConfigKey key) {
    return new Variant(classesJNI.ConfigMap_get(swigCPtr, this, ConfigKey.getCPtr(key), key), false);
  }

  public void set(ConfigKey key, Variant x) {
    classesJNI.ConfigMap_set(swigCPtr, this, ConfigKey.getCPtr(key), key, Variant.getCPtr(x), x);
  }

  public void del(ConfigKey key) {
    classesJNI.ConfigMap_del(swigCPtr, this, ConfigKey.getCPtr(key), key);
  }

  public boolean has_key(ConfigKey key) {
    return classesJNI.ConfigMap_has_key(swigCPtr, this, ConfigKey.getCPtr(key), key);
  }

}
