/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class ConfigVector {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConfigVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfigVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_ConfigVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ConfigVector() {
    this(classesJNI.new_ConfigVector__SWIG_0(), true);
  }

  public ConfigVector(long n) {
    this(classesJNI.new_ConfigVector__SWIG_1(n), true);
  }

  public long size() {
    return classesJNI.ConfigVector_size(swigCPtr, this);
  }

  public long capacity() {
    return classesJNI.ConfigVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    classesJNI.ConfigVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return classesJNI.ConfigVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.ConfigVector_clear(swigCPtr, this);
  }

  public void add(ConfigKey x) {
    classesJNI.ConfigVector_add(swigCPtr, this, ConfigKey.getCPtr(x), x);
  }

  public ConfigKey get(int i) {
    long cPtr = classesJNI.ConfigVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ConfigKey(cPtr, false);
  }

  public void set(int i, ConfigKey val) {
    classesJNI.ConfigVector_set(swigCPtr, this, i, ConfigKey.getCPtr(val), val);
  }

}
