/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Configuration data type. */
public class DataType extends EnumValueDataType {
  protected transient long swigCPtr;

  protected DataType(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.DataType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_DataType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static DataType getUINT64() {
    long cPtr = classesJNI.DataType_UINT64_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getSTRING() {
    long cPtr = classesJNI.DataType_STRING_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getBOOL() {
    long cPtr = classesJNI.DataType_BOOL_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getFLOAT() {
    long cPtr = classesJNI.DataType_FLOAT_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getRATIONAL_PERIOD() {
    long cPtr = classesJNI.DataType_RATIONAL_PERIOD_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getRATIONAL_VOLT() {
    long cPtr = classesJNI.DataType_RATIONAL_VOLT_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getKEYVALUE() {
    long cPtr = classesJNI.DataType_KEYVALUE_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getUINT64_RANGE() {
    long cPtr = classesJNI.DataType_UINT64_RANGE_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getDOUBLE_RANGE() {
    long cPtr = classesJNI.DataType_DOUBLE_RANGE_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getINT32() {
    long cPtr = classesJNI.DataType_INT32_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

  public static DataType getMQ() {
    long cPtr = classesJNI.DataType_MQ_get();
    return (cPtr == 0) ? null : new DataType(cPtr, false);
  }

}
