/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class DeviceVector {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DeviceVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_DeviceVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DeviceVector() {
    this(classesJNI.new_DeviceVector__SWIG_0(), true);
  }

  public DeviceVector(long n) {
    this(classesJNI.new_DeviceVector__SWIG_1(n), true);
  }

  public long size() {
    return classesJNI.DeviceVector_size(swigCPtr, this);
  }

  public long capacity() {
    return classesJNI.DeviceVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    classesJNI.DeviceVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return classesJNI.DeviceVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.DeviceVector_clear(swigCPtr, this);
  }

  public void add(SWIGTYPE_p_std__shared_ptrT_sigrok__Device_t x) {
    classesJNI.DeviceVector_add(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_sigrok__Device_t.getCPtr(x));
  }

  public SWIGTYPE_p_std__shared_ptrT_sigrok__Device_t get(int i) {
    return new SWIGTYPE_p_std__shared_ptrT_sigrok__Device_t(classesJNI.DeviceVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SWIGTYPE_p_std__shared_ptrT_sigrok__Device_t val) {
    classesJNI.DeviceVector_set(swigCPtr, this, i, SWIGTYPE_p_std__shared_ptrT_sigrok__Device_t.getCPtr(val));
  }

}
