/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Exception thrown when an error code is returned by any libsigrok call. */
public class Error {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Error(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Error obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_Error(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Error(int result) {
    this(classesJNI.new_Error(result), true);
  }

  public int getResult() {
    return classesJNI.Error_result_get(swigCPtr, this);
  }

  public String what() {
    return classesJNI.Error_what(swigCPtr, this);
  }

}
