/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** A real hardware device, connected via a driver. */
public class HardwareDevice extends Device {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwnDerived;

  protected HardwareDevice(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.HardwareDevice_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HardwareDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        classesJNI.delete_HardwareDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** Driver providing this device. */
public Driver driver() {
    long cPtr = classesJNI.HardwareDevice_driver(swigCPtr, this);
    return (cPtr == 0) ? null : new Driver(cPtr, true);
  }

}
