/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Payload of a datafeed header packet. */
public class Header extends PacketPayload {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwnDerived;

  protected Header(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.Header_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Header obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        classesJNI.delete_Header(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int feed_version() {
    return classesJNI.Header_feed_version(swigCPtr, this);
  }

  public SWIGTYPE_p_Glib__TimeVal start_time() {
    return new SWIGTYPE_p_Glib__TimeVal(classesJNI.Header_start_time(swigCPtr, this), true);
  }

}
