/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** An input instance (an input format applied to a file or stream) */
public class Input {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Input(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Input obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_Input(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** Virtual device associated with this input. */
public InputDevice device() {
    long cPtr = classesJNI.Input_device(swigCPtr, this);
    return (cPtr == 0) ? null : new InputDevice(cPtr, true);
  }

  /** Send next stream data.
   * @param length Length of data.
   * @param data Next stream data. */
public void send(SWIGTYPE_p_void data, long length) {
    classesJNI.Input_send(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), length);
  }

  /** Signal end of input data. */
public void end() {
    classesJNI.Input_end(swigCPtr, this);
  }

  public void reset() {
    classesJNI.Input_reset(swigCPtr, this);
  }

}
