/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class InputFormatMap {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InputFormatMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InputFormatMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_InputFormatMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InputFormatMap() {
    this(classesJNI.new_InputFormatMap__SWIG_0(), true);
  }

  public InputFormatMap(InputFormatMap arg0) {
    this(classesJNI.new_InputFormatMap__SWIG_1(InputFormatMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return classesJNI.InputFormatMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return classesJNI.InputFormatMap_empty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.InputFormatMap_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__shared_ptrT_sigrok__InputFormat_t get(String key) {
    return new SWIGTYPE_p_std__shared_ptrT_sigrok__InputFormat_t(classesJNI.InputFormatMap_get(swigCPtr, this, key), false);
  }

  public void set(String key, SWIGTYPE_p_std__shared_ptrT_sigrok__InputFormat_t x) {
    classesJNI.InputFormatMap_set(swigCPtr, this, key, SWIGTYPE_p_std__shared_ptrT_sigrok__InputFormat_t.getCPtr(x));
  }

  public void del(String key) {
    classesJNI.InputFormatMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return classesJNI.InputFormatMap_has_key(swigCPtr, this, key);
  }

}
