/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Payload of a datafeed packet with logic data. */
public class Logic extends PacketPayload {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwnDerived;

  protected Logic(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.Logic_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Logic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        classesJNI.delete_Logic(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SWIGTYPE_p_void data_pointer() {
    long cPtr = classesJNI.Logic_data_pointer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public long data_length() {
    return classesJNI.Logic_data_length(swigCPtr, this);
  }

  public long unit_size() {
    return classesJNI.Logic_unit_size(swigCPtr, this);
  }

}
