/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Log verbosity level. */
public class LogLevel extends EnumValueLogLevel {
  protected transient long swigCPtr;

  protected LogLevel(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.LogLevel_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogLevel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_LogLevel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** Output no messages at all. */
  public static final LogLevel NONE = new LogLevel(classesJNI.LogLevel_NONE_get(), false);

  /** Output error messages. */
  public static final LogLevel ERR = new LogLevel(classesJNI.LogLevel_ERR_get(), false);

  /** Output warnings. */
  public static final LogLevel WARN = new LogLevel(classesJNI.LogLevel_WARN_get(), false);

  /** Output informational messages. */
  public static final LogLevel INFO = new LogLevel(classesJNI.LogLevel_INFO_get(), false);

  /** Output debug messages. */
  public static final LogLevel DBG = new LogLevel(classesJNI.LogLevel_DBG_get(), false);

  /** Output very noisy debug messages. */
  public static final LogLevel SPEW = new LogLevel(classesJNI.LogLevel_SPEW_get(), false);


  public static LogLevel getNONE() {
    long cPtr = classesJNI.LogLevel_NONE_get();
    return (cPtr == 0) ? null : new LogLevel(cPtr, false);
  }

  public static LogLevel getERR() {
    long cPtr = classesJNI.LogLevel_ERR_get();
    return (cPtr == 0) ? null : new LogLevel(cPtr, false);
  }

  public static LogLevel getWARN() {
    long cPtr = classesJNI.LogLevel_WARN_get();
    return (cPtr == 0) ? null : new LogLevel(cPtr, false);
  }

  public static LogLevel getINFO() {
    long cPtr = classesJNI.LogLevel_INFO_get();
    return (cPtr == 0) ? null : new LogLevel(cPtr, false);
  }

  public static LogLevel getDBG() {
    long cPtr = classesJNI.LogLevel_DBG_get();
    return (cPtr == 0) ? null : new LogLevel(cPtr, false);
  }

  public static LogLevel getSPEW() {
    long cPtr = classesJNI.LogLevel_SPEW_get();
    return (cPtr == 0) ? null : new LogLevel(cPtr, false);
  }

}
