/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class OptionVector {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptionVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_OptionVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptionVector() {
    this(classesJNI.new_OptionVector__SWIG_0(), true);
  }

  public OptionVector(long n) {
    this(classesJNI.new_OptionVector__SWIG_1(n), true);
  }

  public long size() {
    return classesJNI.OptionVector_size(swigCPtr, this);
  }

  public long capacity() {
    return classesJNI.OptionVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    classesJNI.OptionVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return classesJNI.OptionVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.OptionVector_clear(swigCPtr, this);
  }

  public void add(SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t x) {
    classesJNI.OptionVector_add(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t.getCPtr(x));
  }

  public SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t get(int i) {
    return new SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t(classesJNI.OptionVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t val) {
    classesJNI.OptionVector_set(swigCPtr, this, i, SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t.getCPtr(val));
  }

}
