/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** An option used by an output format. */
public class Option {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Option(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Option obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_Option(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** Short name of this option suitable for command line usage. */
public String id() {
    return classesJNI.Option_id(swigCPtr, this);
  }

  /** Short name of this option suitable for GUI usage. */
public String name() {
    return classesJNI.Option_name(swigCPtr, this);
  }

  /** Description of this option in a sentence. */
public String description() {
    return classesJNI.Option_description(swigCPtr, this);
  }

  /** Default value for this option. */
public Variant default_value() {
    return new Variant(classesJNI.Option_default_value(swigCPtr, this), true);
  }

  /** Possible values for this option, if a limited set. */
public VariantVector values() {
    return new VariantVector(classesJNI.Option_values(swigCPtr, this), true);
  }

  /** Parse a string argument into the appropriate type for this option. */
public Variant parse_string(String value) {
    return new Variant(classesJNI.Option_parse_string(swigCPtr, this, value), true);
  }

}
