/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class OptionMap {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptionMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_OptionMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptionMap() {
    this(classesJNI.new_OptionMap__SWIG_0(), true);
  }

  public OptionMap(OptionMap arg0) {
    this(classesJNI.new_OptionMap__SWIG_1(OptionMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return classesJNI.OptionMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return classesJNI.OptionMap_empty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.OptionMap_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t get(String key) {
    return new SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t(classesJNI.OptionMap_get(swigCPtr, this, key), false);
  }

  public void set(String key, SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t x) {
    classesJNI.OptionMap_set(swigCPtr, this, key, SWIGTYPE_p_std__shared_ptrT_sigrok__Option_t.getCPtr(x));
  }

  public void del(String key) {
    classesJNI.OptionMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return classesJNI.OptionMap_has_key(swigCPtr, this, key);
  }

}
