/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class OutputFormatMap {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OutputFormatMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OutputFormatMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_OutputFormatMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OutputFormatMap() {
    this(classesJNI.new_OutputFormatMap__SWIG_0(), true);
  }

  public OutputFormatMap(OutputFormatMap arg0) {
    this(classesJNI.new_OutputFormatMap__SWIG_1(OutputFormatMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return classesJNI.OutputFormatMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return classesJNI.OutputFormatMap_empty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.OutputFormatMap_clear(swigCPtr, this);
  }

  public SWIGTYPE_p_std__shared_ptrT_sigrok__OutputFormat_t get(String key) {
    return new SWIGTYPE_p_std__shared_ptrT_sigrok__OutputFormat_t(classesJNI.OutputFormatMap_get(swigCPtr, this, key), false);
  }

  public void set(String key, SWIGTYPE_p_std__shared_ptrT_sigrok__OutputFormat_t x) {
    classesJNI.OutputFormatMap_set(swigCPtr, this, key, SWIGTYPE_p_std__shared_ptrT_sigrok__OutputFormat_t.getCPtr(x));
  }

  public void del(String key) {
    classesJNI.OutputFormatMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return classesJNI.OutputFormatMap_has_key(swigCPtr, this, key);
  }

}
