/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Flag applied to output modules. */
public class OutputFlag extends EnumValueOutputFlag {
  protected transient long swigCPtr;

  protected OutputFlag(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.OutputFlag_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OutputFlag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_OutputFlag(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** If set, this output module writes the output itself. */
  public static final OutputFlag INTERNAL_IO_HANDLING = new OutputFlag(classesJNI.OutputFlag_INTERNAL_IO_HANDLING_get(), false);


  public static OutputFlag getINTERNAL_IO_HANDLING() {
    long cPtr = classesJNI.OutputFlag_INTERNAL_IO_HANDLING_get();
    return (cPtr == 0) ? null : new OutputFlag(cPtr, false);
  }

}
