/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** A packet on the session datafeed. */
public class Packet {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Packet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Packet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_Packet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** Type of this packet. */
public PacketType type() {
    long cPtr = classesJNI.Packet_type(swigCPtr, this);
    return (cPtr == 0) ? null : new PacketType(cPtr, false);
  }

  /** Payload of this packet. */
public PacketPayload payload() {
    long cPtr = classesJNI.Packet_payload(swigCPtr, this);
    return (cPtr == 0) ? null : new PacketPayload(cPtr, true);
  }

}
