/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Type of datafeed packet. */
public class PacketType extends EnumValuePacketType {
  protected transient long swigCPtr;

  protected PacketType(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.PacketType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PacketType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_PacketType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** Payload is. */
  public static final PacketType HEADER = new PacketType(classesJNI.PacketType_HEADER_get(), false);

  /** End of stream (no further data). */
  public static final PacketType END = new PacketType(classesJNI.PacketType_END_get(), false);

  /** Payload is struct. */
  public static final PacketType META = new PacketType(classesJNI.PacketType_META_get(), false);

  /** The trigger matched at this point in the data feed. */
  public static final PacketType TRIGGER = new PacketType(classesJNI.PacketType_TRIGGER_get(), false);

  /** Payload is struct. */
  public static final PacketType LOGIC = new PacketType(classesJNI.PacketType_LOGIC_get(), false);

  /** Beginning of frame. */
  public static final PacketType FRAME_BEGIN = new PacketType(classesJNI.PacketType_FRAME_BEGIN_get(), false);

  /** End of frame. */
  public static final PacketType FRAME_END = new PacketType(classesJNI.PacketType_FRAME_END_get(), false);

  /** Payload is struct. */
  public static final PacketType ANALOG = new PacketType(classesJNI.PacketType_ANALOG_get(), false);


  public static PacketType getHEADER() {
    long cPtr = classesJNI.PacketType_HEADER_get();
    return (cPtr == 0) ? null : new PacketType(cPtr, false);
  }

  public static PacketType getEND() {
    long cPtr = classesJNI.PacketType_END_get();
    return (cPtr == 0) ? null : new PacketType(cPtr, false);
  }

  public static PacketType getMETA() {
    long cPtr = classesJNI.PacketType_META_get();
    return (cPtr == 0) ? null : new PacketType(cPtr, false);
  }

  public static PacketType getTRIGGER() {
    long cPtr = classesJNI.PacketType_TRIGGER_get();
    return (cPtr == 0) ? null : new PacketType(cPtr, false);
  }

  public static PacketType getLOGIC() {
    long cPtr = classesJNI.PacketType_LOGIC_get();
    return (cPtr == 0) ? null : new PacketType(cPtr, false);
  }

  public static PacketType getFRAME_BEGIN() {
    long cPtr = classesJNI.PacketType_FRAME_BEGIN_get();
    return (cPtr == 0) ? null : new PacketType(cPtr, false);
  }

  public static PacketType getFRAME_END() {
    long cPtr = classesJNI.PacketType_FRAME_END_get();
    return (cPtr == 0) ? null : new PacketType(cPtr, false);
  }

  public static PacketType getANALOG() {
    long cPtr = classesJNI.PacketType_ANALOG_get();
    return (cPtr == 0) ? null : new PacketType(cPtr, false);
  }

}
