/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class QuantityFlagVector {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QuantityFlagVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QuantityFlagVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_QuantityFlagVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QuantityFlagVector() {
    this(classesJNI.new_QuantityFlagVector__SWIG_0(), true);
  }

  public QuantityFlagVector(long n) {
    this(classesJNI.new_QuantityFlagVector__SWIG_1(n), true);
  }

  public long size() {
    return classesJNI.QuantityFlagVector_size(swigCPtr, this);
  }

  public long capacity() {
    return classesJNI.QuantityFlagVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    classesJNI.QuantityFlagVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return classesJNI.QuantityFlagVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.QuantityFlagVector_clear(swigCPtr, this);
  }

  public void add(QuantityFlag x) {
    classesJNI.QuantityFlagVector_add(swigCPtr, this, QuantityFlag.getCPtr(x), x);
  }

  public QuantityFlag get(int i) {
    long cPtr = classesJNI.QuantityFlagVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new QuantityFlag(cPtr, false);
  }

  public void set(int i, QuantityFlag val) {
    classesJNI.QuantityFlagVector_set(swigCPtr, this, i, QuantityFlag.getCPtr(val), val);
  }

}
