/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** Number represented by a numerator/denominator integer pair. */
public class Rational {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Rational(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Rational obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  /** Numerator, i.e. */
public SWIGTYPE_p_int64_t numerator() {
    return new SWIGTYPE_p_int64_t(classesJNI.Rational_numerator(swigCPtr, this), true);
  }

  /** Denominator, i.e. */
public SWIGTYPE_p_uint64_t denominator() {
    return new SWIGTYPE_p_uint64_t(classesJNI.Rational_denominator(swigCPtr, this), true);
  }

  /** Actual (lossy) value. */
public float value() {
    return classesJNI.Rational_value(swigCPtr, this);
  }

}
