/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** A virtual device associated with a stored session. */
public class SessionDevice extends Device {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwnDerived;

  protected SessionDevice(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.SessionDevice_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SessionDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        classesJNI.delete_SessionDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

}
