/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class SWIGTYPE_p_functionT_void_fstd__shared_ptrT_sigrok__Device_t_std__shared_ptrT_sigrok__Packet_tF_t {
  protected transient long swigCPtr;

  protected SWIGTYPE_p_functionT_void_fstd__shared_ptrT_sigrok__Device_t_std__shared_ptrT_sigrok__Packet_tF_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_functionT_void_fstd__shared_ptrT_sigrok__Device_t_std__shared_ptrT_sigrok__Packet_tF_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_functionT_void_fstd__shared_ptrT_sigrok__Device_t_std__shared_ptrT_sigrok__Packet_tF_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

