/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class TriggerStageVector {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TriggerStageVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TriggerStageVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_TriggerStageVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TriggerStageVector() {
    this(classesJNI.new_TriggerStageVector__SWIG_0(), true);
  }

  public TriggerStageVector(long n) {
    this(classesJNI.new_TriggerStageVector__SWIG_1(n), true);
  }

  public long size() {
    return classesJNI.TriggerStageVector_size(swigCPtr, this);
  }

  public long capacity() {
    return classesJNI.TriggerStageVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    classesJNI.TriggerStageVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return classesJNI.TriggerStageVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.TriggerStageVector_clear(swigCPtr, this);
  }

  public void add(SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerStage_t x) {
    classesJNI.TriggerStageVector_add(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerStage_t.getCPtr(x));
  }

  public SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerStage_t get(int i) {
    return new SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerStage_t(classesJNI.TriggerStageVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerStage_t val) {
    classesJNI.TriggerStageVector_set(swigCPtr, this, i, SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerStage_t.getCPtr(val));
  }

}
