/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** A match condition in a trigger configuration. */
public class TriggerMatch {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TriggerMatch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TriggerMatch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_TriggerMatch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** Channel this condition matches on. */
public Channel channel() {
    long cPtr = classesJNI.TriggerMatch_channel(swigCPtr, this);
    return (cPtr == 0) ? null : new Channel(cPtr, true);
  }

  /** Type of match. */
public TriggerMatchType type() {
    long cPtr = classesJNI.TriggerMatch_type(swigCPtr, this);
    return (cPtr == 0) ? null : new TriggerMatchType(cPtr, false);
  }

  /** Threshold value. */
public float value() {
    return classesJNI.TriggerMatch_value(swigCPtr, this);
  }

}
