/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** A trigger configuration. */
public class Trigger {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Trigger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Trigger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_Trigger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** Name of this trigger configuration. */
public String name() {
    return classesJNI.Trigger_name(swigCPtr, this);
  }

  /** List of the stages in this trigger. */
public TriggerStageVector stages() {
    return new TriggerStageVector(classesJNI.Trigger_stages(swigCPtr, this), true);
  }

  /** Add a new stage to this trigger. */
public TriggerStage add_stage() {
    long cPtr = classesJNI.Trigger_add_stage(swigCPtr, this);
    return (cPtr == 0) ? null : new TriggerStage(cPtr, true);
  }

}
