/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class TriggerMatchVector {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TriggerMatchVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TriggerMatchVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_TriggerMatchVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TriggerMatchVector() {
    this(classesJNI.new_TriggerMatchVector__SWIG_0(), true);
  }

  public TriggerMatchVector(long n) {
    this(classesJNI.new_TriggerMatchVector__SWIG_1(n), true);
  }

  public long size() {
    return classesJNI.TriggerMatchVector_size(swigCPtr, this);
  }

  public long capacity() {
    return classesJNI.TriggerMatchVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    classesJNI.TriggerMatchVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return classesJNI.TriggerMatchVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.TriggerMatchVector_clear(swigCPtr, this);
  }

  public void add(SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerMatch_t x) {
    classesJNI.TriggerMatchVector_add(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerMatch_t.getCPtr(x));
  }

  public SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerMatch_t get(int i) {
    return new SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerMatch_t(classesJNI.TriggerMatchVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerMatch_t val) {
    classesJNI.TriggerMatchVector_set(swigCPtr, this, i, SWIGTYPE_p_std__shared_ptrT_sigrok__TriggerMatch_t.getCPtr(val));
  }

}
