/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

/** A virtual device, created by the user. */
public class UserDevice extends Device {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwnDerived;

  protected UserDevice(long cPtr, boolean cMemoryOwn) {
    super(classesJNI.UserDevice_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UserDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        classesJNI.delete_UserDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** Add a new channel to this device. */
public Channel add_channel(long index, ChannelType type, String name) {
    long cPtr = classesJNI.UserDevice_add_channel(swigCPtr, this, index, ChannelType.getCPtr(type), type, name);
    return (cPtr == 0) ? null : new Channel(cPtr, true);
  }

}
