/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class VariantMap {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VariantMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VariantMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_VariantMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VariantMap() {
    this(classesJNI.new_VariantMap__SWIG_0(), true);
  }

  public VariantMap(VariantMap arg0) {
    this(classesJNI.new_VariantMap__SWIG_1(VariantMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return classesJNI.VariantMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return classesJNI.VariantMap_empty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.VariantMap_clear(swigCPtr, this);
  }

  public Variant get(String key) {
    return new Variant(classesJNI.VariantMap_get(swigCPtr, this, key), false);
  }

  public void set(String key, Variant x) {
    classesJNI.VariantMap_set(swigCPtr, this, key, Variant.getCPtr(x), x);
  }

  public void del(String key) {
    classesJNI.VariantMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return classesJNI.VariantMap_has_key(swigCPtr, this, key);
  }

}
