/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sigrok.core.classes;

public class VariantVector {
  protected transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VariantVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VariantVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        classesJNI.delete_VariantVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VariantVector() {
    this(classesJNI.new_VariantVector__SWIG_0(), true);
  }

  public VariantVector(long n) {
    this(classesJNI.new_VariantVector__SWIG_1(n), true);
  }

  public long size() {
    return classesJNI.VariantVector_size(swigCPtr, this);
  }

  public long capacity() {
    return classesJNI.VariantVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    classesJNI.VariantVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return classesJNI.VariantVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    classesJNI.VariantVector_clear(swigCPtr, this);
  }

  public void add(Variant x) {
    classesJNI.VariantVector_add(swigCPtr, this, Variant.getCPtr(x), x);
  }

  public Variant get(int i) {
    return new Variant(classesJNI.VariantVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Variant val) {
    classesJNI.VariantVector_set(swigCPtr, this, i, Variant.getCPtr(val), val);
  }

}
